### ISSUE TITLE
Request to change API

### ISSUE THREAD

**Issue by salkhon** [mobile-doc/mobile-doc-backend#4]
API Change Request:

## 1. Change Return Format of Doctor Availability Schedule: `/doctor/{doctor_id}`
When the doctor sets his schedule, we'll show a "Week Calendar" and all the 15 minute slots for that week for him to select from in the calendar. The doctor will select all the slots he can avail himself in, that will be his availability schedule. 

Currently on doctor availability you are returning a list of `start time` and `end time` for each weekdays - this provides less flexibility. Rather, provide a list of slots for doctor's availability. For example, 

```
{
availability: {
    "Sunday": [
        "09:30:00", "09:45:00", "14:30:00"...
    ], 
    "Monday": [...]
    ...
    
}
}
```

These times indicate `start time`. Since each slot has a duration of 15 mins, we don't need `end time`. 

## 2. Create an endpoint that gives sessions for user id: `/session/patient/{patient_id}` and `/session/doctor/{doctor_id}`
Currently I am getting patient's appointments from `/patient/EHR/{patient_id}` and doctor's sessions from `/doctor/{doctor_id}` which is inconvenient and inefficient as it gets unnecessary data. 

- Along with the patient and doctor IDs of the session, please send the names of the patient and the doctor in each session to display in the event calendar, otherwise I have to GET the names using another fetch.

## 3. Fix Naming Inconsistencies for Doctor and Patient Appointment Data: 
Doctor `calendar` property lists the appointment times with properties `session_starttime` and `session_endtime`.

Patient session list uses the property `start_time` and `end_time` for session start and end. These time property names should be the same. Currently I have to adapt the `fetch` reponse value based on if the user is a doctor or a patient, which is redundant. 

- Also, we don't need `end time` for sessions. As each session is 15 minute long. If a session runs longer than 15 mins, we'll delay all the latter sessions.

**Comment by MahdeeMushfiqueKamal** [comment]
closing as completed
